# External Services
server:
    port: ${SERVER_PORT:8084}

spring:
    application:
        name: vg-ms-competencies
    data:
        mongodb:
            uri: mongodb+srv://gabrielgutierrezq:3mbmCx8Gx6hrRKHY@as221s5prs2.1e7z9.mongodb.net/AS221S5PRS2?retryWrites=true&w=majority&appName=AS221S5PRS2

# Empoit de actuator
api:
    version: api/v1

# Swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api/competencies

# External services
services:
    didactic-unit:
        url: ${DIDACTIC_UNIT_SERVICE_URL:https://thorough-myrah-vallegrande2-5aeaf151.koyeb.app/common/api/v1/didactic-unit}
